services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - "./apps/backend/dbdata:/var/lib/postgresql/data"
